orocos-toolchain/typelib

- bindings/ruby/lib/typelib/container_type.rb
- bindings/ruby/lib/typelib/type.rb
The elements have already been deleted on the C++ side, and will be
invalidated on the ruby side. However, calling #to_s at that point
would cause a conversion to ruby to occur, which would lead to a crash
> ruby: fix access to soon-to-be invalidated elements when logger level is debug (closes #36)

- typelib/exporter.cc
- typelib/exporter.hh
The string given as filename was not checked for validity after opening
before. This lead to silently _not_ writing to the given filename (if it
is an existing directory for example).
Now the function will throw() if the file could not be opened.
Additionally exceptions are activated for the ofstream-object so that
later failures (like a full disc or unmounted partition) will abort
the execution as well.
Signed-off-by: Martin Zenzes <martin.zenzes@dfki.de>
> exporter: add checks on export-filename, throw if bad

- typelib/value_ops.cc
Including header cstring is required on some systems. (see #47, #48)
There was a misunderstanding on #48 fixed #47 or not. It did not, but this PR does.
> Fix for #47

- bindings/ruby/ext/memory.cc
- bindings/ruby/ext/value.cc
- bindings/ruby/lib/typelib/type.rb
Messing up this one can lead to a free-after-use, as it is used
in the destruction process of the Ruby values during GC
The commit also adds a sanity check in memory_init to detect such
problems.
> ruby: reduce opportunity for clash on on the @registry ivar

- bindings/ruby/lib/typelib/registry_export.rb
- test/ruby/test_registry_export.rb
This one's a far-reaching patch for a bunch of problems in the registry export code. Given its significance, it will probably need some testing before being merged. However, #60 should really be merged ASAP as there is currently some cases where we get into use-after-free (and crash)
1) the filter block could return types that were *not* from the
registry being exported. This broke a few things, and is just
inconsistent, so validate that the return type *is* from the
expected registry
2) when a type has a conversion to ruby, the ruby class is returned.
It is also setup as a subnamespace in the type export hierarchy,
so some methods were defined, and attributes set. Which obviously
breaks if the same type (namely, Array) is used on multiple places
(the last one would win), and is just …
> ruby: fix a bunch of nasty corner cases in the registry export code

- lang/tlb/export.cc
- lang/tlb/import.cc
The metadata system makes a difference between a key that is set to
an empty set of values, and a non-existent key. The TLB import/export
was losing this distinction.
> tlb: support empty metadata keys

- bindings/ruby/lib/typelib/clang.rb
In the current clang installation on Ubuntu 14.04 the binary name apparently has changed to 'clang', currently it fails trying to call 'clang-3.4'.
The method checks which binary is available and enforces to have version 3.4, which seems necessary according to the comments.
> Added a method to find the clang binary, but still enforce to have version 3.4

- bindings/ruby/lib/typelib.rb
Object#singleton_class is built-in since ruby 1.9
> ruby: no need to require utilrb/object/singleton_class anymore

- bindings/ruby/ext/specialized_types.cc
- bindings/ruby/ext/value.cc
- bindings/ruby/lib/typelib.rb
- bindings/ruby/lib/typelib/cxx.rb
- bindings/ruby/lib/typelib/test.rb
- lang/csupport/containers.cc
- test/CMakeLists.txt
- test/ruby/CMakeLists.txt
- test/ruby/test_registry.rb
- test/ruby/test_type.rb
- test/ruby/test_value.rb
- test/test_marshalling.cc
- test/test_memory_layout.cc
- test/test_value_ops_init.cc
- tools/typelib-tlb-merger/test/test-merge-result.tlb
- typelib/memory_layout.cc
- typelib/memory_layout.hh
- typelib/value_ops.cc
This PR implements a more generic initialization method than what was there before. MemoryLayout now contains data layout information (for memcpy/delete/...) but also init information which directs both the container initialization and the initialization of arbitrary parts of the data in memory.
It's used to initialize enums. Enums are the only data values right now that cannot be initialized randomly as the set of values they can take is restricted.
> Initialize enum values

- bindings/ruby/lib/typelib/compound_type.rb
This fixes https://github.com/orocos-toolchain/typelib/issues/73 the issue that compound types couldn't have fields named equal to internal variables.
> added name prefix for instance variables based on the type fields

- bindings/ruby/lib/typelib/clang.rb
The defines should be forwarded to the clang importer because they might change how the analysed header files look. Some headers become unparsable when defines are missing.
> clang.rb: Forward defines to typelib-clang-tlb-importer

- lang/csupport/containers.cc
- lang/csupport/containers.hh
- typelib/memory_layout.hh
- typelib/value_ops.cc
- typelib/value_ops.hh
This was a simplifying assumption, but GCC 5 breaks it for std::string.
Do the proper thing, and init/copy elements one by one when resizing
the vector requires a reallocation.
This fixes SEGV if resizing vectors of strings (or of compounds that contain strings) under GCC5
> do not assume that vector and string do not have pointers internally that point to themselves

- lang/csupport/standard_types.cc
This fixes the following error on ARM-based platforms:
terminate called after throwing an instance of 'Typelib::Undefined'
what():  undefined type '/int33_t'
> Fix registration of wchar_t by properly identifying its underlying type

- test/test_memory_layout.cc
- typelib/memory_layout.cc
- typelib/memory_layout.hh
There was a bug in removeTrailingSkips that was the sibling of
https://github.com/orocos-toolchain/typelib/issues/55. That is,
the removeTrailingSkips method would corrupt the layout if the
one-before-last element was 8 (FLAG_SKIP), regardless of the rest,
as e.g.
FLAG_ARRAY 8
FLAG_MEMCPY 8
FLAG_END
This commit removes removeTrailingSkip, instead integrating the
functionality in simplify() -- which is working while parsing the
ops structure forward instead of backwards.
> integrate trailing-skip removal in simplify

- bindings/ruby/lib/typelib/clang.rb
Ubuntu 16.04 only provide clang versions 3.5, 3.6, 3.7 and 3.8.
This patch lets typelib accept any 3.x version (if need be, this should be replaced by a regex for 3.4 or newer
> Enable compatibility with newer clang versions

- bindings/ruby/lib/typelib/gccxml.rb
- test/ruby/cxx_common_tests.rb
- test/ruby/cxx_import_tests/bug_opaque_import.hh
- test/ruby/test_cxx_castxml.rb
find_node_by_name would fail to filter on node_type when the node could
be resolved directly. This would lead to the opaque resolution assuming
that it is a typedef, and then usage of a nil value
> castxml: fix corner case in opaque resolution

- typelib/typedisplay.cc
- typelib/typedisplay.hh
Adds the missing visit method for containers and adds some more output-informations to compound and numeric.
Example for new output:
compound /base/samples/Pointcloud_m [56] {
(+0) compound /base/Time [8] {
(+0) sint(8) (/int64_t) microseconds
}; time
(+8) container /std/vector</wrappers/Matrix</double,3,1>> points
(+32) container /std/vector</wrappers/Matrix</double,4,1>> colors
};
> Extends type-display.

- test/ruby/test_specialized_types.rb
- typelib/typemodel.hh
The default equality would lead to having all null types be equal.
> fix null type equality to only compare on name

- bindings/ruby/lib/typelib/registry.rb
- bindings/ruby/lib/typelib/registry_export.rb
The call was so far used to reset-and-setup. One can now, by
calling it without arguments, just reset the export when e.g.
the registry itself is reset.
> ruby: allow to reset an existing export with reset_registry_export

- bindings/ruby/lib/typelib/gccxml.rb
Some rawflags like the -std option may change the preprocessor
output (i.e. through #if c++ standard ...)
> pass the rawflags to the preprocessor

- bindings/ruby/lib/typelib/gccxml.rb
- test/ruby/cxx_common_tests.rb
- test/ruby/cxx_import_tests/documentation_metadata_tags.h
This allows to set arbitrary metadata from a type documentation.
See test file documentation_metadata_tags.h for an example
> ruby: allow setting metadata from a type or field documentation

- bindings/ruby/lib/typelib.rb
- test/ruby/test_specialized_types.rb
- test/ruby/test_type.rb
This is for consistency, mostly, as Typelib::Type is never used directly
> ruby: initialize Typelib::Type.metadata to an empty metadata set

- bindings/ruby/lib/typelib.rb
- bindings/ruby/lib/typelib/compound_type.rb
- manifest.xml
'dup' has been defined on immediate values in Ruby 2.4, use backports
to get it for older Ruby versions
> ruby: use 'backports' to avoid an explicit check on the availability of #dup

- manifest.xml
- package.xml
I updated the `package.xml`, which - as far as I know - is only used by ROS tools, and merged the recent dependency changes from master. Like this, it can be compiled using ROS and catkin.
I am not sure about the changes in `manifest.xml`. Most likely they would break the autoproj bootstrap procedure, right? If yes, the alternative would be to submit a PR to https://github.com/ros/rosdistro/tree/master/rosdep/rosdep.yaml and add the key `ruby-dev` there.
The [differences](https://github.com/orocos-toolchain/typelib/compare/master...toolchain-2.9) between [toolchain-2.9](https://github.com/orocos-toolchain/typelib/tree/toolchain-2.9) and [master](https://github.com/orocos-toolchain/typelib/tree/master) are actually quite small. Is it desirable to submit individual PRs targeting `master` …
> toolchain-2.9: fix rosdep compatibility of manifest.xml and merge recent changes to package.xml

- bindings/ruby/lib/typelib/type.rb
- test/ruby/test_compound_type.rb
- test/ruby/test_numeric_type.rb
It wouldn't be wrong per se, but having converted types after .new
is quite unexpected in the current usage of the API. Since the API
does not support "switching" between using raw access and Ruby access
at the same time, it can lead to hard-to-debug issues.
> ruby: make sure we apply any ruby type used within #initialize in .new

- CMakeLists.txt
Cxx11 is equired because of the use of std::unique_ptr
solves: 
https://github.com/orocos-toolchain/typelib/issues/115
> set cxx11 as default

- lang/csupport/containers.cc
- test/ruby/container_memory_leak_on_resize.rb
- test/ruby/test_container_type.rb
In case of resize, the elements of the old container would not
be deleted, which leaks if the container's elements have
containers themselves
> fix memory leak in container resizing

- test/test_display.cc
- typelib/pluginmanager.cc
Typelib curretnly fails to build on debian testing with gcc9 with following error:
```
/opt/rock/tools/typelib/typelib/pluginmanager.cc: In static member function 'static void Typelib::PluginManager::save(const string&, const utilmm::config_set&, const Typelib::Registry&, std::ostream&)':
/opt/rock/tools/typelib/typelib/pluginmanager.cc:176:35: error: 'parameter' function with trailing return type not declared with 'auto' type specifier
176 |     unique_ptr<Exporter> exporter(PluginManager::self()->exporter(kind));
|                                   ^~~~~~~~~~~~~
```
This PR fixes the error by declaring the PluginManager::self() call with an auto object and use the object afterwards to call ->exporter(kind) on it.
> fix compilation error with gcc9

- bindings/ruby/lib/typelib/gccxml.rb
- test/CMakeLists.txt
- test/ruby/cxx_import_tests/empty_base_class.hh
- test/ruby/cxx_import_tests/empty_base_class.tlb
- test/ruby/cxx_tlbgen.in
These "empty types" do not affect the binary representation of
the struct, and are therefore safe to manipulate from Typelib's
perspective.
Note that this fixes the test failure regarding std::pair, which on
recent GCCs (C++11) derives from a private empty type
> allow types without fields and virtual methods as base classes for any accessor

- bindings/ruby/lib/typelib/gccxml.rb
- test/ruby/cxx_common_tests.rb
- test/ruby/cxx_import_tests/documentation_metadata_tags.h
- test/ruby/test_cxx.rb
Even beyond trailing spaces (which one should remove, but we
all know how it goes), a C++ comment can be
~~~ cpp
/* @meta key value */
~~~
Which causes the value to have a trailing space.
> ruby: strip spaces from metadata value

- bindings/ruby/ext/memory.cc
The signature of functions in st_hash_type changed, update
them for versions of Ruby >= 2.7
> fix compatibility with Ruby 2.7

- bindings/ruby/lib/typelib/gccxml.rb
- test/ruby/cxx_import_tests/relative_includes.hh
- test/ruby/test_cxx_castxml.rb
castxml will report a relative path if given explicitely on
the command line, or if it is resolves through the include path
and the include path has .. in it.
That is, -I/some/path/../bla will lead to a file path that
includes ..
Expand all of them. There was already some normalization done
at the end of the chain, but this was failing if the relative
path is given on the command line (thus completely making the
load fail).
> normalize the File name attributes by expanding them

- bindings/ruby/lib/typelib/cxx.rb
- manifest.xml
- package.xml
master version of #133.
As discussed in #132.
I would  prefer that these changes would also end up in `toolchain-2.9`.
> Make CastXML the default instead of GccXML (master)

- test/test_display.cc
_Fixes https://github.com/orocos-toolchain/typelib/pull/128#issuecomment-768656215 ([failed Travis CI job](https://github.com/orocos-toolchain/orocos_toolchain/pull/41/checks?check_run_id=1778156440))._
This patch is required for building on Ubuntu Xenial 16.04 with Boost 1.56. Everything else seems to work fine.
At least all unit tests pass if I set `TYPELIB_CXX_LOADER=castxml` manually:
```sh
(xenial)johannes@im-laptop-007:/tmp/orocos/build/typelib$ export TYPELIB_CXX_LOADER=castxml
(xenial)johannes@im-laptop-007:/tmp/orocos/build/typelib$ ctest
Test project /tmp/orocos/build/typelib
Start 1: RubyInstalledPlugins
1/4 Test #1: RubyInstalledPlugins .............   Passed   12.48 sec
Start 2: RubyLocalPlugins
2/4 Test #2: RubyLocalPlugins .................   Passed   12.85 sec
Start 3: …
```
> Fix boost/test/floating_point_comparison.hpp include in test_display.cc for Boost 1.59 and older

- bindings/ruby/ext/value.cc
- bindings/ruby/lib/typelib/type.rb
- test/ruby/test_value.rb
Type.new returns a value that is not zeroed out, but whose enums
and containers are properly initialized. Type.zero now offers the
same, but allowing to zero the structure first.
> define Type.zero which creates a value that's pre-zeroed out then initialized

- bindings/ruby/lib/typelib/cxx.rb
- bindings/ruby/lib/typelib/gccxml.rb
Unlike for gccxml, with castxml we have to parse file-by-file. While
this reduces performance in principle (headers have to be re-parsed
over and over again), it also allows for parallelization between the
castxml instances and the Ruby parsing method.
Implement this parallelization scheme. For base/orogen/types, which
is infamously slow, we get (on a quad-core i7 with 16 GB RAM, so no
issue with disk caching)
~~~
time TYPELIB_CASTXML_PARALLEL=1 make regen
110,85s user 3,55s system 100% cpu 1:54,01 total
time TYPELIB_CASTXML_PARALLEL=2 make regen
121,59s user 4,20s system 143% cpu 1:27,88 total
time TYPELIB_CASTXML_PARALLEL=3 make regen
137,41s user 4,76s system 195% cpu 1:12,66 total
time TYPELIB_CASTXML_PARALLEL=4 make regen
144,81s user 4,88s system 216% cpu 1:09,25 total
~~~
> allow to load C++ files in parallel
